import React, { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { useForm } from "react-hook-form";
import axios from 'axios'


const inter = Inter({ subsets: ['latin'] })

function Post() {
  const [categoryname, setCategoryName] = useState('');
    
    //const onSubmit = data => console.log(data);
    const handleSubmit = async (event) => {
      event.preventDefault();
      try {
        const response = await axios.post('http://localhost:3000/categories', {
          category: {
            categoryname,
          }
        });
        console.log(response.data);
        // フォームをリセット
        setCategoryName('');
      } catch (error) {
        console.error(error);
      }
    };
  
  const style = {
      input: {
        width: '500px',
        height: '40px', /* サイズを変更したい高さに設定 */
      },
      textarea: {
        width: '500px',
        height: '300px',
      },
      button: {
        width: '50px',
        height: '30px'
      }
  };
        
    
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.s}>
         <div className={styles.a}>
          <ul>
           <li>
            <Link href="/">
             <p>トップ</p>
            </Link>
           </li>
           <li>
            <Link href="/post">
             <p>登録</p>
            </Link>
           </li>
           <li>
            <Link href="/check">
             <p>管理</p>
            </Link>
           </li>
           <li>
            <Link href="/confirmation">
             <p>ユーザー</p>
            </Link>
           </li>
          </ul>
        </div>
        <div className='form'>
         <h1>カテゴリーを追加</h1>
        <Link href="/post">
          <p>商品登録ページへ</p>
        </Link>
         <div>
         <form onSubmit={handleSubmit}>
            <h3>カテゴリー名</h3>
            <input style={style.input} type='text' id='categoryname' value={categoryname} onChange={(event) => setCategoryName(event.target.value)} required/>
            <button type="submit">登録</button>
          </form>
         </div>
        </div>
      </div>
    </>
  )
}




export default Post;
