import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import axios from 'axios'
import { useRouter } from 'next/router'


const inter = Inter({ subsets: ['latin'] })
//ページネーション
const ITEMS_PER_PAGE = 10;

function Check({initialData}) {
  const [data, setData] = useState(initialData);
  const router = useRouter();

  const [currentPage, setCurrentPage] = useState(1); // 現在表示しているページ番号
  const totalPages = Math.ceil(initialData.length / ITEMS_PER_PAGE); // 総ページ数
  const startIndex = (currentPage - 1) * ITEMS_PER_PAGE; // 現在表示するページの先頭アイテムのインデックス
  const endIndex = Math.min(startIndex + ITEMS_PER_PAGE, initialData.length); // 現在表示するページの末尾アイテムのインデックス

  // 現在表示するページのデータを取得(ページネーション)
  const currentPageData = initialData.slice(startIndex, endIndex);

  const pagination = [];
  for (let i = 1; i <= totalPages; i++) {
    pagination.push(
      <button key={i} onClick={() => handlePageChange(i)}>
        {i}
      </button>
    );
  }

  const items = [];
  for (let i = 0; i < currentPageData.length; i++) {
    const item = currentPageData[i];
    items.push(
      <div key={item.id}>
        <p>{item.id}</p>
        <p>{item.categoryname}</p>
        <button onClick={() => handleDelete(item.id)}>削除</button>
      </div>
    );
  }

  // ページ番号が変更された場合に呼ばれる関数
  const handlePageChange = (pageNumber) => {
    setCurrentPage(pageNumber);
  };


  async function handleUpdate(id, uddatedData) {
    const response = await axios.get(`http://api:3000/categories/${id}`, uddatedData);
    setData(response.data);
  }

  
  //削除機能
  const handleDelete = async (id) => {
    try {
      // DELETEリクエストを送信
      const response = await axios.delete(`http://api:3000/categories/${id}`);
      //リロードせずに表示
      setData((prevData) => prevData.filter((item) => item.id !== id));
      // レスポンスを処理する
      console.log(response.data);
    } catch (error) {
      // エラーを処理する
      console.error(error);
    }
  };

  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.s}>
        <div className={styles.a}>
          <ul>
           <li>
            <Link href="/">
             <p>トップ</p>
            </Link>
           </li>
           <li>
            <Link href="/post">
             <p>登録</p>
            </Link>
           </li>
           <li>
            <Link href="/check">
             <p>管理</p>
            </Link>
           </li>
           <li>
            <Link href="/confirmation">
             <p>ユーザー</p>
            </Link>
           </li>
          </ul>
        </div>
        <div>
        <h1>カテゴリー一覧</h1>
        <Link href="/check">
          <p>商品一覧ページへ</p>
        </Link>
          {items}
          <div>
            {pagination}
          </div>
        </div>
      </div>
    </>
  )
}

export async function getStaticProps() {
  const response = await axios.get('http://api:3000/categories?page=1');
  const initialData = response.data;
  return { props: { initialData } };
}



export default Check;

