import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import axios from 'axios'


const inter = Inter({ subsets: ['latin'] })

function Home() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.s}>
      <div className={styles.a}>
          <ul>
           <li>
            <Link href="/">
             <p>トップ</p>
            </Link>
           </li>
           <li>
            <Link href="/post">
             <p>登録</p>
            </Link>
           </li>
           <li>
            <Link href="/check">
             <p>管理</p>
            </Link>
           </li>
           <li>
            <Link href="/confirmation">
             <p>ユーザー</p>
            </Link>
           </li>
          </ul>
        </div>
      </div>
    </>
  )
}
export default Home;
