# MySQL. Versions 5.5.8 and up are supported.
・・・
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
+ password: password
- host: localhost
+ host: db

development:
  <<: *default
- database: app_development
+ database: sample
・・・